// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirtualDoormanAspNet.Models;

namespace VirtualDoormanAspNet.Migrations
{
    [DbContext(typeof(VirtualDoormanAspNetContext))]
    [Migration("20191120152050_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VirtualDoormanAspNet.Models.ResidentialData", b =>
                {
                    b.Property<string>("Cnpj")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Cnpj");

                    b.ToTable("ResidentialData");
                });
#pragma warning restore 612, 618
        }
    }
}
